name: 'zuora'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

vars:
  zuora: 
    account: "{{ source('zuora', 'account') }}" 
    amendment: "{{ source('zuora', 'amendment') }}"
    contact: "{{ source('zuora', 'contact') }}"
    credit_balance_adjustment: "{{ source('zuora', 'credit_balance_adjustment') }}"
    invoice: "{{ source('zuora', 'invoice') }}"
    invoice_item: "{{ source('zuora', 'invoice_item') }}"
    invoice_payment: "{{ source('zuora', 'invoice_payment') }}" 
    order: "{{ source('zuora', 'order') }}" 
    payment: "{{ source('zuora', 'payment') }}"
    payment_method: "{{ source('zuora', 'payment_method') }}"
    product_rate_plan_charge: "{{ source('zuora', 'product_rate_plan_charge') }}"
    product_rate_plan: "{{ source('zuora', 'product_rate_plan') }}"
    product: "{{ source('zuora', 'product') }}"
    rate_plan_charge: "{{ source('zuora', 'rate_plan_charge') }}"
    rate_plan: "{{ source('zuora', 'rate_plan') }}"
    refund: "{{ source('zuora', 'refund') }}"
    refund_invoice_payment: "{{ source('zuora', 'refund_invoice_payment') }}"
    subscription: "{{ source('zuora', 'subscription') }}"
    taxation_item: "{{ source('zuora', 'taxation_item') }}"

  zuora_account_pass_through_columns: []
  zuora_rate_plan_pass_through_columns: []
  zuora_rate_plan_charge_pass_through_columns: []
  zuora_subscription_pass_through_columns: []

models:
  zuora:
    +schema: zuora
    +materialized: table
    intermediate:
      +schema: zuora_int
      +materialized: table
    staging:
      +schema: zuora_source
      +materialized: view

  
