{% macro get_invoice_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "account_id", "datatype": dbt.type_string()},
    {"name": "adjustment_amount", "datatype": dbt.type_float()},
    {"name": "amount", "datatype": dbt.type_float()}, 
    {"name": "amount_home_currency", "datatype": dbt.type_float()},
    {"name": "amount_without_tax", "datatype": dbt.type_float()}, 
    {"name": "amount_without_tax_home_currency", "datatype": dbt.type_float()},
    {"name": "auto_pay", "datatype": "boolean"},
    {"name": "balance", "datatype": dbt.type_float()},
    {"name": "bill_to_contact_id", "datatype": dbt.type_string()},
    {"name": "comments", "datatype": dbt.type_string()},
    {"name": "created_by_id", "datatype": dbt.type_string()},
    {"name": "created_date", "datatype": dbt.type_timestamp()},
    {"name": "credit_balance_adjustment_amount", "datatype": dbt.type_float()},
    {"name": "credit_memo_amount", "datatype": dbt.type_float()},
    {"name": "default_payment_method_id", "datatype": dbt.type_string()},
    {"name": "due_date", "datatype": "date"},
    {"name": "exchange_rate", "datatype": dbt.type_float()},
    {"name": "exchange_rate_date", "datatype": "date"},
    {"name": "home_currency", "datatype": dbt.type_string()},
    {"name": "id", "datatype": dbt.type_string()},
    {"name": "includes_one_time", "datatype": "boolean"},
    {"name": "includes_recurring", "datatype": "boolean"},
    {"name": "includes_usage", "datatype": "boolean"},
    {"name": "invoice_date", "datatype": "date"},
    {"name": "invoice_number", "datatype": dbt.type_string()},
    {"name": "last_email_sent_date", "datatype": dbt.type_timestamp()},
    {"name": "parent_account_id", "datatype": dbt.type_string()},
    {"name": "payment_amount", "datatype": dbt.type_float()},
    {"name": "payment_term", "datatype": dbt.type_string()},
    {"name": "posted_by", "datatype": dbt.type_string()},
    {"name": "posted_date", "datatype": dbt.type_timestamp()}, 
    {"name": "refund_amount", "datatype": dbt.type_float()},  
    {"name": "sold_to_contact_id", "datatype": dbt.type_string()},
    {"name": "source", "datatype": dbt.type_string()},
    {"name": "source_id", "datatype": dbt.type_string()},
    {"name": "source_type", "datatype": dbt.type_string()},
    {"name": "status", "datatype": dbt.type_string()},
    {"name": "target_date", "datatype": "date"},
    {"name": "tax_amount", "datatype": dbt.type_float()},
    {"name": "tax_status", "datatype": dbt.type_string()},
    {"name": "transaction_currency", "datatype": dbt.type_string()},
    {"name": "transferred_to_accounting", "datatype": dbt.type_string()},
    {"name": "updated_by_id", "datatype": dbt.type_string()},
    {"name": "updated_date", "datatype": dbt.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}